FROM node:20-alpine
 
WORKDIR /app
 
ENV CI=true

COPY .yarn ./.yarn
COPY jsconfig.json package.json yarn.lock .yarnrc.yml .pnp.cjs .pnp.loader.mjs ./
COPY src ./src
COPY bin ./bin

RUN yarn set version 4.0.1
RUN yarn install --immutable

RUN yarn run build:bin
 
ENV NODE_ENV=production
CMD ["yarn", "node", "build/put-image.js"]
